model: "gpt2" # option: ["gpt2", "gpt2-medium", "gpt2-large", "gpt2-xl"]
wandb_mode: "online" # option: ["offline", "disabled"]
dataset_path: "dataset"
device: "cpu" # or "cpu"
checkpoint_path: "/home/zhiyi/Desktop/Projects/CS4NLP/MixtureOfExpertMathReasoning/num_step_6/"
test_data_path: "/home/zhiyi/Desktop/Projects/CS4NLP/MixtureOfExpertMathReasoning/dataset/test_6_steps.json"
transformers_cache_dir: None